#!/usr/bin/env bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Copyright 2014 - Øyvind 'bolt' Hvidsten   <bolt@dhampir.no>

! ${GHOST:-false} || return 0

function httptitle_grab
{
	curl -m5 "$@"
}

function httptitle_do
{
	local url words title i loc domain
	read -a words <<<"$@"
	for url in "${words[@]}"; do
		[[ "$url" =~ https?://.+ ]] || continue
		for ((i=0; i<5; i++)); do
			loc=$(httptitle_grab -I "$url" | sed -n 's/^Location: //p' | tr -d '\r\n')
			[[ -n "$loc" ]] || break
			url=$loc
		done
		title=$(
			httptitle_grab "$url" 2>/dev/null |
			perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si' 2>/dev/null
		)
		[[ -n "$title" ]] || continue
		if type recode >/dev/null 2>&1; then
			title=$(recode utf8..h <<<"$title" | sed 's/&amp;/\&/g' | recode h..utf8)
		fi
		domain=$(cut -d\/ -f 3 <<<"$url")
		domain=${domain#www.*}
		say "$target" "$title ($domain)"
	done
}

if
	[[ "$cmd" = "PRIVMSG" ]] &&
	[[ "$target" = "#"* ]] &&
	[[ -n "$data" ]] &&
	[[ -z "$reply" ]]
then
	httptitle_do "$data"
fi
